import matplotlib.pyplot as plt
figure, axes = plt.subplots()
plt.xlim(-10,10)
plt.ylim(-10,10)


axes.add_artist( plt.Circle(( 0 , 0 ), 10,color='blue',fill=False ))
axes.add_artist( plt.Circle(( 0 , 0 ), 1,color='red',fill=True ))
axes.add_artist( plt.Circle(( 4 , 0 ), 1,color='red',fill=True ))
axes.add_artist( plt.Circle(( 8 , 0 ), 1,color='red',fill=True ))
axes.add_artist( plt.Circle(( -4 , 0 ), 1,color='red',fill=True ))
axes.add_artist( plt.Circle(( -8 , 0 ), 1,color='red',fill=True ))
axes.add_artist( plt.Circle((  4, 4), 1,color='red',fill=True ))
axes.add_artist( plt.Circle(( 4 , 8 ), 1,color='red',fill=True ))
axes.add_artist( plt.Circle(( 8 , 4 ), 1,color='red',fill=True ))
axes.add_artist( plt.Circle((  -4, 4), 1,color='red',fill=True ))
axes.add_artist( plt.Circle(( -4 , 8 ), 1,color='red',fill=True ))
axes.add_artist( plt.Circle(( -8 , 4 ), 1,color='red',fill=True ))
axes.add_artist( plt.Circle(( -8 , -4 ), 1,color='red',fill=True ))
axes.add_artist( plt.Circle((  -4, 4), 1,color='red',fill=True ))
axes.add_artist( plt.Circle(( -4 , -8 ), 1,color='red',fill=True ))
axes.add_artist( plt.Circle(( -8 , -4 ), 1,color='red',fill=True ))
axes.add_artist( plt.Circle(( -8 , -4 ), 1,color='red',fill=True ))
axes.add_artist( plt.Circle((  0, 4), 1,color='red',fill=True ))
axes.add_artist( plt.Circle(( 0 , 8 ), 1,color='red',fill=True ))
axes.add_artist( plt.Circle((  0, -4), 1,color='red',fill=True ))
axes.add_artist( plt.Circle(( 0 , -8 ), 1,color='red',fill=True ))
axes.add_artist( plt.Circle(( -8 , 4 ), 1,color='red',fill=True ))
axes.add_artist( plt.Circle(( -8 , -4 ), 1,color='red',fill=True ))
axes.add_artist( plt.Circle((  4, -4), 1,color='red',fill=True ))
axes.add_artist( plt.Circle(( 4 , -8 ), 1,color='red',fill=True ))
axes.add_artist( plt.Circle((  -4, -4), 1,color='red',fill=True ))
axes.add_artist( plt.Circle((  8, -4), 1,color='red',fill=True ))


plt.title( 'CORE_arrangement' )
plt.figure(figsize=(15,15))
plt.show()
